### ISSUE TITLE
Does not work with current version of Token Action HUD Core

### ISSUE THREAD

**Issue by WEKarnesky** [pwatson100/token-action-hud-alien#1]
Current version (1.0.2) reports the following error when Token Action HUD v1.5.1 is installed
 
> The installed Token Action HUD system module requires Token Action HUD Core module version 1.4. Install the required version to continue using Token Action HUD.

**Comment by pwatson100** [comment]
Thanks.  I am aware. As the TAH Core team say you will need to stay on the 1.4 version until I have updated it.

**Comment by pwatson100** [comment]
New version released.
